### ISSUE TITLE
[Bug] Incorrect filter for public wishlists of other people

### ISSUE THREAD

**Issue by pommernMeg** [Janis-1979/Ingress-Swag-Database-Issue-Tracker#33]
Browser: [Version 1.71.121 Chromium: 130.0.6723.91 (Offizieller Build) (64-Bit)](https://brave.com/latest/)
OS: Linux

If I look at a public Wish List of another person and change the filter to e.g. Pins then I seem to see a different amount than the Wish List filtered to Pins

Reproduction steps:

Link from Hulk: https://www.ingress-swag.com/wishlist/hulk32/

Change the filter there to Pin

![1](https://github.com/user-attachments/assets/4d5515fd-1c6c-4c8a-92ac-f407ed28161e)

Result:
![2](https://github.com/user-attachments/assets/9434b527-e3a7-42de-a050-654ad340bc4b)

Cross-check with a filter that is not on my wishlist.
Biocard sets

I then get all Biocard sets displayed although it can already be seen above that at least one Biocard set is on Hulk's wish list

![3](https://github.com/user-attachments/assets/1115ef22-eb58-4aa7-be0e-fb09a0ad0331)

**Comment by Janis-1979** [comment]
Problem found. 
URL should be https://www.ingress-swag.com/wishlist/hulk32/?Sorting=ASC&s=&swagtype=pins&items_per_page=36&markings=0&filter= if Filter is set.

But currently URL is https://www.ingress-swag.com/?Sorting=ASC&s=&swagtype=pins&items_per_page=36&markings=0&filter=
