### ISSUE TITLE
Create a public tg channel populated with new uploads

### ISSUE THREAD

**Issue by Hulk32** [Janis-1979/Ingress-Swag-Database-Issue-Tracker#34]
Similar to https://t.me/r3f1s_swag, a general telegram public channel with all new uploaded items would ease tracking and fixing them.

**Comment by Janis-1979** [comment]
**To-Do**:
- Add new table to store which swag type uploads should be posted in which groups (group-id and thread-id)
- Add Api support to subscribe the upload messages
- Add Api support to unsubscribe the upload messages
- Add methods to send messages to all subscribed chats after uploading new swag items

Message contains:
- Front image
- Back image
- Title with link to the swag item
- Categories
- Description
